<?php
/**
 * Velocity CMS Cache Handler
 * Auto-generated by Lightspeed CMS client
 */

require_once 'lightspeed/cms.php';

header('Content-Type: application/json');

$operation = $_GET['operation'] ?? 'list';
$type = $_GET['type'] ?? null;
$id = $_GET['id'] ?? null;

if ($operation === 'clear') {
    if ($id) {
        cms()->clearCacheForAll($id, $type ?? 'content');
        echo json_encode(['status' => 'ok', 'operation' => 'clear', 'cleared' => ['type' => $type ?? 'content', 'id' => $id]]);
    } else {
        cms()->clearCache();
        echo json_encode(['status' => 'ok', 'operation' => 'clear', 'cleared' => 'all']);
    }
    exit;
}

// List cache contents
$entries = [];
$prefix = 'lightspeed_cms_';

if (function_exists('apcu_cache_info') && class_exists('APCUIterator')) {
    foreach (new APCUIterator('/^' . preg_quote($prefix, '/') . '/') as $item) {
        $data = $item['value'];
        $entries[] = [
            'key' => $item['key'],
            'cached_at' => date('c', $data['cached_at'] ?? 0),
            'stale_at' => date('c', $data['stale_at'] ?? 0),
            'is_stale' => time() > ($data['stale_at'] ?? 0),
            'etag' => $data['etag'] ?? null,
            'content_length' => strlen($data['content'] ?? ''),
            'ttl' => $item['ttl'],
            'hits' => $item['num_hits'],
        ];
    }
}

echo json_encode([
    'status' => 'ok',
    'enabled' => function_exists('apcu_fetch') && apcu_enabled(),
    'entries' => $entries,
    'count' => count($entries),
]);